
-- Create table for Zepto Assortment Data
create table public.zepto_assortment (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  scraped_at timestamp with time zone,
  name text,
  brand text,
  mrp numeric,
  price numeric,
  pack_size text,
  category text,
  subcategory text,
  availability text,
  inventory integer,
  store_id text,
  base_product_id text,
  shelf_life_in_hours text,
  eta text,
  pincode_input text,
  clicked_label text
);

-- Enable Row Level Security (RLS)
alter table public.zepto_assortment enable row level security;

-- Create policy to allow all actions for now (or customize as needed)
create policy "Enable all access for all users" on public.zepto_assortment
for all using (true) with check (true);
